[package]
name = "FPCasino"
version = "0.1.0"
authors = ["erlangxk <simon.xikun@gmail.com>"]

[dependencies]
maplit = "1.0.1"
rand = "0.4.2"
lazy_static = "1.0.0"
jsonrpc-core = "8.0.1"
jsonrpc-macros = "8.0.0"
jsonrpc-http-server = "8.0.0"